### ISSUE TITLE
STI problem. Solved rolling back to 0.18.0

### ISSUE THREAD

**Issue by CV-Gate** [drapergem/draper#487]
Hello, after updating Draper to last version my STI based model didn't work anymore. 

I got the error Draper::UninferrableDecoratorError - Could not infer a decorator 

Had to roll back to 0.18.0

Any idea?

Thanks!

This is the error log:

```
 (gem) draper-1.1.0/lib/draper.rb:49:in `initialize'
  (gem) draper-1.1.0/lib/draper/decoratable.rb:66:in `rescue in decorator_class'
  (gem) draper-1.1.0/lib/draper/decoratable.rb:63:in `decorator_class'
  (gem) draper-1.1.0/lib/draper/decoratable.rb:55:in `decorate'
  (gem) activerecord-3.2.11/lib/active_record/relation/delegation.rb:37:in `block in method_missing'
  (gem) activerecord-3.2.11/lib/active_record/relation.rb:241:in `block in scoping'
  (gem) activerecord-3.2.11/lib/active_record/scoping.rb:98:in `with_scope'
  (gem) activerecord-3.2.11/lib/active_record/relation.rb:241:in `scoping'
  (gem) activerecord-3.2.11/lib/active_record/relation/delegation.rb:37:in `method_missing'
  app/controllers/galleries_controller.rb:4:in `index'
  (gem) actionpack-3.2.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  (gem) actionpack-3.2.11/lib/abstract_controller/base.rb:167:in `process_action'
  (gem) actionpack-3.2.11/lib/action_controller/metal/rendering.rb:10:in `process_action'
  (gem) actionpack-3.2.11/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:425:in `_run__1376253648959277642__process_action__3248835966836243842__callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
  (gem) actionpack-3.2.11/lib/abstract_controller/callbacks.rb:17:in `process_action'
  (gem) actionpack-3.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
  (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `block in instrument'
  (gem) activesupport-3.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  (gem) activesupport-3.2.11/lib/active_support/notifications.rb:123:in `instrument'
  (gem) actionpack-3.2.11/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  (gem) actionpack-3.2.11/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  (gem) activerecord-3.2.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  (gem) actionpack-3.2.11/lib/abstract_controller/base.rb:121:in `process'
  (gem) actionpack-3.2.11/lib/abstract_controller/rendering.rb:45:in `process'
  (gem) actionpack-3.2.11/lib/action_controller/metal.rb:203:in `dispatch'
  (gem) actionpack-3.2.11/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  (gem) actionpack-3.2.11/lib/action_controller/metal.rb:246:in `block in action'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:36:in `call'
  (gem) journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:601:in `call'
  (gem) meta_request-0.2.2/lib/meta_request/middlewares/app_request_handler.rb:11:in `call'
  (gem) rack-contrib-1.1.0/lib/rack/contrib/response_headers.rb:17:in `call'
  (gem) meta_request-0.2.2/lib/meta_request/middlewares/headers.rb:16:in `call'
  (gem) meta_request-0.2.2/lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  (gem) bullet-4.3.1/lib/bullet/rack.rb:11:in `call'
  (gem) request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
  (gem) warden-1.2.1/lib/warden/manager.rb:35:in `block in call'
  (gem) warden-1.2.1/lib/warden/manager.rb:34:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  (gem) rack-1.4.5/lib/rack/etag.rb:23:in `call'
  (gem) rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/head.rb:14:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/flash.rb:242:in `call'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  (gem) activerecord-3.2.11/lib/active_record/query_cache.rb:64:in `call'
  (gem) activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `_run__729313215061186803__call__776963980825659591__callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:65:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  (gem) better_errors-0.7.0/lib/better_errors/middleware.rb:84:in `protected_app_call'
  (gem) better_errors-0.7.0/lib/better_errors/middleware.rb:79:in `better_errors_call'
  (gem) better_errors-0.7.0/lib/better_errors/middleware.rb:56:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  (gem) railties-3.2.11/lib/rails/rack/logger.rb:32:in `call_app'
  (gem) railties-3.2.11/lib/rails/rack/logger.rb:16:in `block in call'
  (gem) activesupport-3.2.11/lib/active_support/tagged_logging.rb:22:in `tagged'
  (gem) railties-3.2.11/lib/rails/rack/logger.rb:16:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  (gem) rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  (gem) rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  (gem) activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  (gem) rack-1.4.5/lib/rack/lock.rb:15:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/static.rb:62:in `call'
  (gem) railties-3.2.11/lib/rails/engine.rb:479:in `call'
  (gem) railties-3.2.11/lib/rails/application.rb:223:in `call'
  (gem) rack-1.4.5/lib/rack/content_length.rb:14:in `call'
  (gem) railties-3.2.11/lib/rails/rack/log_tailer.rb:17:in `call'
  (gem) rack-1.4.5/lib/rack/handler/webrick.rb:59:in `service'
```

**Comment by kolosek** [comment]
How nice when somebody had discussion 2 years ago, which solves your problem :) :+1:

**Comment by kalashnikovisme** [comment]
You can try 
```ruby
VehicleDecorator.decorate(@vehicle)
```
in your controller.
