### ISSUE TITLE
Rails 4.2 / active_model_serializers issue

### ISSUE THREAD

**Issue by kapso** [drapergem/draper#651]
I am seeing this error after I upgraded to `active_model_serializers v0.9.3` which I am using for API controllers. It works fine with `active_model_serializers v0.9.2`

```
/Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/draper-1.4.0/lib/draper/railtie.rb:48:in `block (2 levels) in <class:Railtie>': uninitialized constant ActiveModel::ArraySerializerSupport (NameError)
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/draper-1.4.0/lib/draper/railtie.rb:47:in `block in <class:Railtie>'
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/kapil/.rbenv/versions/2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
```

This does not work:
```ruby
gem 'active_model_serializers', '0.9.3'
gem 'draper', '1.4.0'
gem 'rails', '4.2.0'
```

This works:
```ruby
gem 'active_model_serializers', '0.9.2'
gem 'draper', '1.4.0'
gem 'rails', '4.2.0'
```

**Comment by tricknotes** [comment]
This is the same issue as https://github.com/drapergem/draper/issues/644

**Comment by jcasimir** [comment]
Believed fixed with 2.0. Reopen if necessary.

**Comment by AbdullahAlger** [comment]
I had the same problem today. Once I changed from 0.9.3 to 0.9.2, `UserSerializer.new(User.first).to_json` started working. With 0.9.3, it had the following error message

```
NameError: uninitialized constant UserSerializer
	from (irb):5
	from /Users/Abdullah-Mac/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/Abdullah-Mac/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/Abdullah-Mac/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/Abdullah-Mac/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/Abdullah-Mac/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/Abdullah-Mac/code/angular/angular-rails-task-list/bin/rails:8:in `<top (required)>'
	from /Users/Abdullah-Mac/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Abdullah-Mac/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by Aupajo** [comment]
Ran into this after installing `ember-rails`:

```
/Users/pete/.gem/ruby/2.2.2/gems/draper-1.4.0/lib/draper/railtie.rb:48:in `block (2 levels) in <class:Railtie>': uninitialized constant ActiveModel::ArraySerializerSupport (NameError)
	from /Users/pete/.gem/ruby/2.2.2/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /Users/pete/.gem/ruby/2.2.2/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /Users/pete/.gem/ruby/2.2.2/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /Users/pete/.gem/ruby/2.2.2/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /Users/pete/.gem/ruby/2.2.2/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /Users/pete/.gem/ruby/2.2.2/gems/draper-1.4.0/lib/draper/railtie.rb:47:in `block in <class:Railtie>'
	from /Users/pete/.gem/ruby/2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/pete/.gem/ruby/2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
	from /Users/pete/.gem/ruby/2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/pete/.gem/ruby/2.2.2/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/pete/.gem/ruby/2.2.2/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
	from /Users/pete/Workspace/project/config/environment.rb:5:in `<top (required)>'
	from /Users/pete/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:92:in `preload'
	from /Users/pete/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
	from /Users/pete/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /Users/pete/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /Users/pete/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /Users/pete/.gem/ruby/2.2.2/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/pete/.rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by Aupajo** [comment]
Scrap that, was using Draper 1.4.

**Comment by vmanamino** [comment]
Just to confirm : 0.9.2 worked for me, while 0.9.3 caused the NameError

**Comment by rvsingh** [comment]
I think, I am facing the same issue.
Rails 4.2.6
ruby 2.2.3p173 
active_model_serializers (0.9.4)

`/config/initializers/active_model_serializers.rb:3:in `<top (required)>': uninitialized constant ActiveModelSerializers (NameError)
        from /Users/rajveershekhawat/.rvm/gems/ruby-2.2.3@rails426/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
        from /Users/rajveershekhawat/.rvm/gems/ruby-2.2.3@rails426/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
        from /Users/rajveershekhawat/.rvm/gems/ruby-2.2.3@rails426/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
        from /Users/rajveershekhawat/.rvm/gems/ruby-2.2.3@rails426/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'`
