### ISSUE TITLE
Suddenly register_spec_type error

### ISSUE THREAD

**Issue by hendricius** [drapergem/draper#679]
Hi everyone,

thanks for the great gem. Suddenly out of nothing I am receiving a `register_spec_type` error. No idea, for my colleagues it works, no longer on my machine.

I have the draper `2.1.0` version with ruby `2.2.2` and rails `4.2.2`

Any idea what could cause this?

Here is the full stacktrace.

```
➜  tripl_app git:(staging) bin/rake --trace
** Invoke default (first_time)
** Invoke test (first_time)
** Execute test
** Invoke test:run (first_time)
** Execute test:run
rake aborted!
NoMethodError: undefined method `register_spec_type' for Draper::TestCase:Class
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/draper-2.1.0/lib/draper/test/minitest_integration.rb:2:in `<class:TestCase>'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/draper-2.1.0/lib/draper/test/minitest_integration.rb:1:in `<top (required)>'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/draper-2.1.0/lib/draper/railtie.rb:56:in `block (2 levels) in <class:Railtie>'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/lazy_load_hooks.rb:44:in `each'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-rails-2.2.0/lib/minitest/rails.rb:155:in `<top (required)>'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/Users/hendricius/code/tripl/tripl_app/test/test_helper.rb:4:in `<top (required)>'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/Users/hendricius/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
```

**Comment by seuros** [comment]
`spring stop` :smile_cat:

**Comment by hendricius** [comment]
Ok so apparently I had to do this in the `minitest_integration.rb`.

```
class Draper::TestCase
  Minitest::Spec.register_spec_type(self) do |desc|
    desc < Draper::Decorator || desc < Draper::CollectionDecorator if desc.is_a?(Class)
  end
  Minitest::Spec.register_spec_type(/Decorator( ?Test)?\z/i, self)
end
```

Same issue appears on all our macs in our team. Linux runs perfectly fine.

**Comment by manuelmeurer** [comment]
Running into the same problem:

```
$ bundle exec rake test --trace
** Invoke default (first_time)
** Invoke test (first_time)
** Execute test
** Invoke test:run (first_time)
** Execute test:run
rake aborted!
NoMethodError: undefined method `register_spec_type' for Draper::TestCase:Class
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/draper-2.1.0/lib/draper/test/minitest_integration.rb:2:in `<class:TestCase>'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/draper-2.1.0/lib/draper/test/minitest_integration.rb:1:in `<top (required)>'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/draper-2.1.0/lib/draper/railtie.rb:56:in `block (2 levels) in <class:Railtie>'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:44:in `each'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-rails-2.2.0/lib/minitest/rails.rb:155:in `<top (required)>'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/manuel/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/Users/manuel/code/myapp/test/test_helper.rb:5:in `<top (required)>'
```

My `test_helper.rb`:

```ruby
ENV['RAILS_ENV'] = 'test'

require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
require 'minitest/rails'
require 'minitest/reporters'
require 'webmock/minitest'

Minitest::Reporters.use! \
  Minitest::Reporters::ProgressReporter.new,
  ENV,
  Minitest.backtrace_filter

class ActiveSupport::TestCase
  fixtures :all
end
```

How did you change `minitest_integration.rb`, @hendricius? Do you use a forked version of Draper?

**Comment by manuelmeurer** [comment]
Eventually I managed to fix this issue by replacing the individual `require '.../railtie'` calls in `config/application.rb` with `require 'rails/all'`.

**Comment by xymbol** [comment]
@manuelmeurer Encountered the same issue. We found the commented out:

```
require "rails/test_unit/railtie"
```

to be the culprit. Otherwise, things load in an unexpected sequence.

**Comment by manuelmeurer** [comment]
@xymbol Which version of Rails are you using? `test_unit` shouldn't be in there in Rails >= 4 AFAIK.

**Comment by xymbol** [comment]
@manuelmeurer These are the first few lines of `config/application.rb` in a newly generated Rails 4.2.7 app using the `-T` option. The integration is still named `test_unit` even when it uses `minitest`.

```
require File.expand_path('../boot', __FILE__)

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "sprockets/railtie"
# require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Blog
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
```

**Comment by manuelmeurer** [comment]
Ah interesting, never noticed that...

**Comment by codebycliff** [comment]
I don't think this is an issue anymore. I tried to reproduce it on a brand new Rails 4.2.2 / Ruby 2.2.2 / Draper 2.1.0 without any luck. Changing `require 'rails/all'` to the individual railties (with test_unit) commented out as mentioned in the comment above did cause issues. But uncommenting the `require "rails/test_unit/railtie"` made things work again. 

If this is still an issue for someone, please comment and I'll look into it again.
