### ISSUE TITLE
Ruby 2.2 on Rails 3.2 support

### ISSUE THREAD

**Issue by leomao10** [drapergem/draper#690]
Hello, I'm getting this error, when I tried to run `bundle exec rake`:

```ruby
/Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require': Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (cannot load such file -- test/unit/testcase) (LoadError)
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/test_case.rb:2:in `<top (required)>'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /Users/leo/.gem/ruby/2.2.2/gems/draper-1.3.0/lib/draper/test_case.rb:11:in `rescue in <module:Draper>'
	from /Users/leo/.gem/ruby/2.2.2/gems/draper-1.3.0/lib/draper/test_case.rb:7:in `<module:Draper>'
	from /Users/leo/.gem/ruby/2.2.2/gems/draper-1.3.0/lib/draper/test_case.rb:1:in `<top (required)>'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /Users/leo/.gem/ruby/2.2.2/gems/draper-1.3.0/lib/draper/railtie.rb:21:in `block in <class:Railtie>'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:34:in `call'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:42:in `each'
	from /Users/leo/.gem/ruby/2.2.2/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
	from /Users/leo/.gem/ruby/2.2.2/gems/railties-3.2.22/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
	from /Users/leo/.gem/ruby/2.2.2/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/leo/.gem/ruby/2.2.2/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `run'
	from /Users/leo/.gem/ruby/2.2.2/gems/railties-3.2.22/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/leo/.gem/ruby/2.2.2/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `each'
	from /Users/leo/.gem/ruby/2.2.2/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/leo/.gem/ruby/2.2.2/gems/railties-3.2.22/lib/rails/application.rb:136:in `initialize!'
	from /Users/leo/.gem/ruby/2.2.2/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/leo/reInteractive/acconline/acctv-online/config/environment.rb:5:in `<top (required)>'
	from /Users/leo/reInteractive/acconline/acctv-online/spec/spec_helper.rb:3:in `require'
	from /Users/leo/reInteractive/acconline/acctv-online/spec/spec_helper.rb:3:in `<top (required)>'
	from /Users/leo/reInteractive/acconline/acctv-online/spec/controllers/admin/packages_controller_spec.rb:1:in `require'
	from /Users/leo/reInteractive/acconline/acctv-online/spec/controllers/admin/packages_controller_spec.rb:1:in `<top (required)>'
	from /Users/leo/.gem/ruby/2.2.2/gems/rspec-core-2.14.6/lib/rspec/core/configuration.rb:896:in `load'
	from /Users/leo/.gem/ruby/2.2.2/gems/rspec-core-2.14.6/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
	from /Users/leo/.gem/ruby/2.2.2/gems/rspec-core-2.14.6/lib/rspec/core/configuration.rb:896:in `each'
	from /Users/leo/.gem/ruby/2.2.2/gems/rspec-core-2.14.6/lib/rspec/core/configuration.rb:896:in `load_spec_files'
	from /Users/leo/.gem/ruby/2.2.2/gems/rspec-core-2.14.6/lib/rspec/core/command_line.rb:22:in `run'
	from /Users/leo/.gem/ruby/2.2.2/gems/rspec-core-2.14.6/lib/rspec/core/runner.rb:80:in `run'
	from /Users/leo/.gem/ruby/2.2.2/gems/rspec-core-2.14.6/lib/rspec/core/runner.rb:17:in `block in autorun'
```

I also tried in v1.4.0, and it throws the same error. I think the reason is [test-unit and minitest was removed in ruby 2.2](https://bugs.ruby-lang.org/issues/9711)

**Comment by lucianosousa** [comment]
@leomao10 
```
Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'`
```

Did you try this?

**Comment by leomao10** [comment]
Yes, I just tried, and it worked. 

The problem is I use 'rspec' rather than 'test-unit'. So I don't like the idea to add 'test-unit' in my Gemfile.

But I guess what I should really do is to upgrade my rails to 4.x....

**Comment by lucianosousa** [comment]
@leomao10 thats right.
it's a rails dependency, not a draper one.

**Comment by leomao10** [comment]
I see, thanks for your quick response :) I will close the issue now.

Cheers
