### ISSUE TITLE
Draper rails-5 + ActionController::API

### ISSUE THREAD

**Issue by bdmac** [drapergem/draper#753]
Unable to load rails console using Rails 5 + the rails-5 branch of draper if my ApplicationController inherits from `ActionController::API` instead of `ActionController::Base`. Full stack trace below.

Steps to repro:
1. Take any Rails 5 app using draper.
2. Change ApplicationController parent class to be `ActionController::API` instead of `ActionController::Base`.
3. Run `rails console`.

```
/Users/bdmac/.gem/ruby/2.3.0/bundler/gems/draper-3c165152041f/lib/draper/view_context.rb:8:in `view_context': super: no superclass method `view_context' for #<ApplicationController:0x007ff0e76167c0> (NoMethodError)
Did you mean?  view_runtime
    from /Users/bdmac/.gem/ruby/2.3.0/bundler/gems/draper-3c165152041f/lib/draper/railtie.rb:62:in `block in <class:Railtie>'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:226:in `block in run_console_blocks'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:247:in `each'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:247:in `each_registered_block'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:226:in `run_console_blocks'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:463:in `block in run_console_blocks'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine/railties.rb:13:in `each'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine/railties.rb:13:in `each'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:463:in `run_console_blocks'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:442:in `load_console'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/console.rb:34:in `initialize'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `new'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /Users/bdmac/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by seanlinsley** [comment]
Does this affect `rails server` as well, or only `rails console`?

**Comment by bdmac** [comment]
Will let you know once I can get our tests passing lol. Was trying to run console to debug stuff.   
  
  
 ~ Brian McManus  
  
  

  
  
  
  

  
  
>

**Comment by bdmac** [comment]
@seanlinsley it does indeed seem to only impact `rails console`. Server starts up normally.

**Comment by seanlinsley** [comment]
@bdmac please give #754 a try

**Comment by codebycliff** [comment]
Support for Rails 5 API-only should be in master as of https://github.com/drapergem/draper/pull/793 being merged.
