### ISSUE TITLE
View context 'controller' method errors during rails console startup on Rails 5.1

### ISSUE THREAD

**Issue by malacalypse** [drapergem/draper#798]
Hello, on Draper 3.0.0.pre1 in Rails 5.1 I'm getting the following error during application startup in rails console:

```
/Users/user/.rvm/gems/ruby-2.4.0/gems/actionpack-5.1.0/lib/action_controller/test_case.rb:39:in `create': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from /Users/user/.rvm/gems/ruby-2.4.0/gems/draper-3.0.0.pre1/lib/draper/view_context/build_strategy.rb:41:in `block in controller'
```

It looks like:

```
 39         def controller
 40           (Draper::ViewContext.controller || ApplicationController.new).tap do |controller|
 41             controller.request ||= ActionController::TestRequest.create
 42           end
```

Should be changed to something like:

```
 39         def controller
 40           (Draper::ViewContext.controller || ApplicationController.new).tap do |controller|
 41             controller.request ||= ActionController::TestRequest.create(controller)
 42           end
```

No?

There's also a note:

```
 26   # ActionController::TestCase will be deprecated and moved to a gem in Rails 5.1.
 27   # Please use ActionDispatch::IntegrationTest going forward.
```

Any plans to mitigate this as well?

**Comment by codebycliff** [comment]
This is fixed in master. I'm hoping to get an official release out on RubyGems by the end of the week.

**Comment by malacalypse** [comment]
Ok, cool, thanks.
